### ISSUE TITLE
version 1.4.4 Fixed Windows XP compatibility，but version 2.0 is not compatible with windows XP

### ISSUE THREAD

**Issue by liuying1129** [starmessage/libSoftMeter#17]

**Comment by starmessage** [comment]
v2.0.3 seems to be ok with Windows XP from our end.
Please send to our email more details about the problem (so we can reproduce it) and also the log file.

**Comment by starmessage** [comment]
Your log contains the HTTP status code 403 (forbitten).
In Windows XP, SoftMeter tries to send the hits using the http protocol (not https).
This is because the old ciphers of Windows XP are not accepted by modern servers, e.g. Google Analytics.
Recently GA stopped accepting the non-HTTPS requests and this is why these cannot be logged from Windows XP.
There is nothing we can do about this.
